export type BookmarkItem = {
  name: string;
  url: string;
  desc: string;
};

export type BookmarkSection = {
  category: string;
  items: BookmarkItem[];
};

const bookmarks: Record<'zh' | 'en', BookmarkSection[]> = {
  zh: [
    { category: "开发者工具", items: [
      { name: "Regex101", url: "https://regex101.com/", desc: "在线正则表达式测试与调试工具。" },
      { name: "CyberChef", url: "https://gchq.github.io/CyberChef/", desc: "极其强大的网络瑞士军刀，支持各种数据格式转换与加解密操作。" },
      { name: "AST Explorer", url: "https://astexplorer.net/", desc: "语法树分析与探索工具。" },
      { name: "JSON Crack", url: "https://jsoncrack.com/", desc: "直观地将 JSON 数据可视化为图表。" },
      { name: "Vercel", url: "https://vercel.com/", desc: "前端项目极速部署平台与 Serverless 托管服务。" }
    ]},
    { category: "设计与灵感", items: [
      { name: "Awwwards", url: "https://www.awwwards.com/", desc: "全球优秀的网页设计灵感与评选。" },
      { name: "Fontshare", url: "https://www.fontshare.com/", desc: "免费高质量商用字体服务。" },
      { name: "Dribbble", url: "https://dribbble.com/", desc: "探索全球顶尖设计师的创意与交互设计作品。" },
      { name: "Figma", url: "https://www.figma.com/", desc: "基于云端的现代化高保真界面设计与原型制作工具。" }
    ]},
    { category: "阅读与学习", items: [
      { name: "MDN Web Docs", url: "https://developer.mozilla.org/", desc: "Web 开发的终极指南与参考文档。" },
      { name: "Hacker News", url: "https://news.ycombinator.com/", desc: "科技圈前沿新闻与高质量极客讨论区。" },
      { name: "arXiv", url: "https://arxiv.org/", desc: "康奈尔大学运营的开放获取论文库（追踪物理、数学与AI计算机前沿研究）。" },
      { name: "GitHub Trending", url: "https://github.com/trending", desc: "发现今天 GitHub 开源社区中最炽手可热的黑马库。" }
    ]}
  ],
  en: [
    { category: "Developer Tools", items: [
      { name: "Regex101", url: "https://regex101.com/", desc: "Online regex tester and debugger." },
      { name: "CyberChef", url: "https://gchq.github.io/CyberChef/", desc: "The Cyber Swiss Army Knife - a web app for encryption, encoding, and data operations." },
      { name: "AST Explorer", url: "https://astexplorer.net/", desc: "Web tool to explore ASTs generated by various parsers." },
      { name: "JSON Crack", url: "https://jsoncrack.com/", desc: "Seamlessly visualize your JSON data instantly into graphs." },
      { name: "Vercel", url: "https://vercel.com/", desc: "The platform for frontend developers, providing the speed and reliability innovators need." }
    ]},
    { category: "Design & Inspiration", items: [
      { name: "Awwwards", url: "https://www.awwwards.com/", desc: "Design inspiration and awards." },
      { name: "Fontshare", url: "https://www.fontshare.com/", desc: "Free fonts service from Indian Type Foundry." },
      { name: "Dribbble", url: "https://dribbble.com/", desc: "Discover the world's top designers & creatives." },
      { name: "Figma", url: "https://www.figma.com/", desc: "The collaborative interface design and prototyping tool." }
    ]},
    { category: "Reading & Learning", items: [
      { name: "MDN Web Docs", url: "https://developer.mozilla.org/", desc: "The go-to resource for web development." },
      { name: "Hacker News", url: "https://news.ycombinator.com/", desc: "Tech news and high-quality discussions." },
      { name: "arXiv", url: "https://arxiv.org/", desc: "Open access to e-prints in Physics, Mathematics, Computer Science, and AI." },
      { name: "GitHub Trending", url: "https://github.com/trending", desc: "See what the global GitHub open-source community is most excited about today." }
    ]}
  ]
};

const pageText = {
  zh: {
    title: "收藏 | Jay Yu",
    heading: "bookmarks",
    intro: '一些我觉得非常有用的网站、工具、资源的精选，更多网站请参考我的资源导航网站：',
    navLinkText: 'JayYuの资源导航',
    navLinkUrl: 'https://jayyu686.top/'
  },
  en: {
    title: "Bookmarks | Jay Yu",
    heading: "bookmarks",
    intro: 'A curated list of useful websites, tools, and resources. For more, check out my resource navigation site: ',
    navLinkText: "JayYu's Resource Nav",
    navLinkUrl: 'https://jayyu686.top/'
  }
};

export function getBookmarks(lang: 'zh' | 'en') {
  return bookmarks[lang];
}

export function getBookmarksPageText(lang: 'zh' | 'en') {
  return pageText[lang];
}
